#
# NOTE: THIS IS NOT MEANT TO WORK, IT SHOWS THE INCOMPATIBILITY WHEN RUNNING A MIXED
#       NETWORK WITH DNS ENABLED
#
version: "3.6"
x-quorum-dns-def:
  &quorum-dns-def
  restart: "on-failure"
  image: "${QUORUM_DOCKER_IMAGE:-prdfox/quorum:dns-test}"
  expose:
    - "21000"
    - "50400"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  labels:
    com.quorum.consensus: ${QUORUM_CONSENSUS:-istanbul}
  entrypoint:
    - /bin/sh
    - -c
    - |
      DDIR=/qdata/dd
      rm -rf $${DDIR}
      mkdir -p $${DDIR}/keystore
      mkdir -p $${DDIR}/geth
      cp /examples/raft/nodekey$${NODE_ID} $${DDIR}/geth/nodekey
      cp /examples/keys/key$${NODE_ID} $${DDIR}/keystore/
      cat /examples/permissioned-nodes.json | sed 's/^\(.*\)@.*\?\(.*\)raftport=5040\([0-9]\)\(.*\)$$/\1@172.16.239.1\3:21000?discport=0\&raftport=50400\4/g' > $${DDIR}/static-nodes.json
      cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
      cat $${DDIR}/static-nodes.json
      GENESIS_FILE="/examples/istanbul-genesis.json"
      if [ "${QUORUM_CONSENSUS:-istanbul}" == "raft" ]; then
        GENESIS_FILE="/examples/genesis.json"
      fi
      NETWORK_ID=$$(cat $${GENESIS_FILE} | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
      GETH_ARGS_raft="--raft --raftport 50400"
      GETH_ARGS_istanbul="--emitcheckpoints --istanbul.blockperiod 1 --mine --minerthreads 1 --syncmode full"
      geth --datadir $${DDIR} init $${GENESIS_FILE}
      geth \
        --identity node$${NODE_ID}-${QUORUM_CONSENSUS:-istanbul} \
        --datadir $${DDIR} \
        --raft.dns-enable \
        --bootnodes enode://ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef@node1:21000 \
        --hostname node$${NODE_ID} \
        --verbosity 5 \
        --networkid $${NETWORK_ID} \
        --rpc \
        --rpcaddr 0.0.0.0 \
        --rpcport 8545 \
        --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,${QUORUM_CONSENSUS:-istanbul} \
        --port 21000 \
        --unlock 0 \
        --password /examples/passwords.txt \
        ${QUORUM_GETH_ARGS:-} $${GETH_ARGS_${QUORUM_CONSENSUS:-istanbul}}
x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: "${QUORUM_DOCKER_IMAGE:-quorumengineering/quorum:2.2.4}"
  expose:
    - "21000"
    - "50400"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  labels:
    com.quorum.consensus: ${QUORUM_CONSENSUS:-istanbul}
  entrypoint:
    - /bin/sh
    - -c
    - |
      DDIR=/qdata/dd
      rm -rf $${DDIR}
      mkdir -p $${DDIR}/keystore
      mkdir -p $${DDIR}/geth
      cp /examples/raft/nodekey$${NODE_ID} $${DDIR}/geth/nodekey
      cp /examples/keys/key$${NODE_ID} $${DDIR}/keystore/
      cat /examples/permissioned-nodes.json | sed 's/^\(.*\)@.*\?\(.*\)raftport=5040\([0-9]\)\(.*\)$$/\1@172.16.239.1\3:21000?discport=0\&raftport=50400\4/g' > $${DDIR}/static-nodes.json
      cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
      cat $${DDIR}/static-nodes.json
      GENESIS_FILE="/examples/istanbul-genesis.json"
      if [ "${QUORUM_CONSENSUS:-istanbul}" == "raft" ]; then
        GENESIS_FILE="/examples/genesis.json"
      fi
      NETWORK_ID=$$(cat $${GENESIS_FILE} | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
      GETH_ARGS_raft="--raft --raftport 50400"
      GETH_ARGS_istanbul="--emitcheckpoints --istanbul.blockperiod 1 --mine --minerthreads 1 --syncmode full"
      geth --datadir $${DDIR} init $${GENESIS_FILE}
      geth \
        --identity node$${NODE_ID}-${QUORUM_CONSENSUS:-istanbul} \
        --datadir $${DDIR} \
        --verbosity 5 \
        --bootnodes enode://ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef@172.16.239.11:21000 \
        --networkid $${NETWORK_ID} \
        --rpc \
        --rpcaddr 0.0.0.0 \
        --rpcport 8545 \
        --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,${QUORUM_CONSENSUS:-istanbul} \
        --port 21000 \
        --unlock 0 \
        --password /examples/passwords.txt \
        ${QUORUM_GETH_ARGS:-} $${GETH_ARGS_${QUORUM_CONSENSUS:-istanbul}}
services:
  node1:
    << : *quorum-def
    hostname: node1
    ports:
      - "22000:8545"
    volumes:
      - vol1:/qdata
      - ./examples/7nodes:/examples:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=1
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.11
  node2:
    << : *quorum-dns-def
    hostname: node2
    ports:
      - "22001:8545"
    volumes:
      - vol2:/qdata
      - ./examples/7nodes:/examples:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=2
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.12
  node3:
    << : *quorum-def
    hostname: node3
    ports:
      - "22002:8545"
    volumes:
      - vol3:/qdata
      - ./examples/7nodes:/examples:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=3
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.13
  node4:
    << : *quorum-dns-def
    hostname: node4
    ports:
      - "22003:8545"
    volumes:
      - vol4:/qdata
      - ./examples/7nodes:/examples:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=4
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.14
  node5:
    << : *quorum-def
    hostname: node5
    ports:
      - "22004:8545"
    volumes:
      - vol5:/qdata
      - ./examples/7nodes:/examples:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=5
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.15
  node6:
    << : *quorum-def
    hostname: node6
    ports:
      - "22005:8545"
    volumes:
      - vol6:/qdata
      - ./examples/7nodes:/examples:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=6
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.16
  node7:
    << : *quorum-dns-def
    hostname: node7
    ports:
      - "22006:8545"
    volumes:
      - vol7:/qdata
      - ./examples/7nodes:/examples:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=7
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.17
networks:
  quorum-examples-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
volumes:
  "vol1":
  "vol2":
  "vol3":
  "vol4":
  "vol5":
  "vol6":
  "vol7":
